const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-IN').format(n);
const fleet=[
{id:1,name:'Mahindra Scorpio N',daily_price:5500,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/MahindraScorpioIndia.jpg'},
{id:2,name:'Toyota Fortuner',daily_price:7500,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Fortuner%20Full.jpg'},
{id:3,name:'Mahindra Scorpio Classic',daily_price:4500,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/Mahindra%20Scorpio%20S11%20.jpg'},
{id:4,name:'Mahindra Thar',daily_price:5000,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/Mahindra%20Thar%20SUV%20in%20%22Red%20Rage%22%20color%20at%20Ashiana%20Brahmanda%2C%20East%20Singbhum%20India%20%28Ank%20Kumar%2C%20Infosys%20limited%29%2002%20%28cropped%29.jpg'},
{id:5,name:'Toyota Innova Crysta',daily_price:5800,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Innova%20Crysta%202.4%20Z%20front%20right.jpg'},
{id:6,name:'Maruti Suzuki Swift Dzire',daily_price:2800,image_url:'https://commons.wikimedia.org/wiki/Special:FilePath/Suzuki%20Dzire%202024%20ZXI%2B.jpg'}];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const grid=$('#fleetGrid');
if(grid) grid.innerHTML=fleet.map((c,i)=>`<article class="car-card">
<img class="car-img" src="${esc(c.image_url)}" alt="${esc(c.name)}" referrerpolicy="no-referrer"/>
<div class="car-shade"></div><div class="car-top"><span class="availability">AVAILABLE</span><span class="car-index">0${i+1}</span></div>
<div class="car-info"><div><h3>${esc(c.name)}</h3><div class="rate"><strong>₹${money(c.daily_price)}</strong> / day</div></div><button class="reserve-btn" title="Preview only">↗</button></div>
</article>`).join('');
document.addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px');const g=$('#cursorGlow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
if(window.gsap){gsap.registerPlugin(ScrollTrigger);gsap.from('.nav',{y:-30,opacity:0,duration:.7});gsap.from('.hero-copy>*',{y:32,opacity:0,stagger:.08,duration:.9,ease:'power3.out'});gsap.utils.toArray('.car-card').forEach((el,i)=>gsap.from(el,{y:60,opacity:0,duration:.75,delay:(i%2)*.05,scrollTrigger:{trigger:el,start:'top 90%'}}));}
if(!matchMedia('(pointer:coarse)').matches){$$('.car-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${-y*4}deg) rotateY(${x*5}deg) translateY(-2px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
const ownerBtn=$('#ownerPreviewBtn'), ownerDialog=$('#ownerPreviewDialog'), ownerClose=$('#ownerPreviewClose');
if(ownerBtn&&ownerDialog) ownerBtn.addEventListener('click',()=>ownerDialog.showModal());
if(ownerClose&&ownerDialog) ownerClose.addEventListener('click',()=>ownerDialog.close());
if(ownerDialog) ownerDialog.addEventListener('click',e=>{if(e.target===ownerDialog) ownerDialog.close()});
async function initThree(){try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js');const canvas=$('#heroCanvas');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,100);camera.position.set(.2,1.1,8.4);const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);const car=new THREE.Group();const dark=new THREE.MeshPhysicalMaterial({color:0x101820,metalness:.9,roughness:.22,clearcoat:1});const glass=new THREE.MeshPhysicalMaterial({color:0x7891a3,roughness:.05,transmission:.25,transparent:true,opacity:.75});const tire=new THREE.MeshStandardMaterial({color:0x040506,roughness:.85});const rim=new THREE.MeshStandardMaterial({color:0xa7b0b8,metalness:.95,roughness:.15});const body=new THREE.Mesh(new THREE.BoxGeometry(4.4,1.05,1.82),dark);body.position.y=.35;car.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(2.3,.95,1.56),glass);cabin.position.set(-.45,1.25,0);car.add(cabin);for(const x of [-1.45,1.43])for(const z of [-.88,.88]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.52,.52,.36,32),tire);w.rotation.x=Math.PI/2;w.position.set(x,.12,z);car.add(w);const r=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.38,12),rim);r.rotation.x=Math.PI/2;r.position.copy(w.position);car.add(r)}car.position.set(2.9,-.05,0);car.rotation.y=-.4;scene.add(car);scene.add(new THREE.HemisphereLight(0xddeeff,0x080808,2.4));const key=new THREE.DirectionalLight(0xffe29a,3.3);key.position.set(4,6,4);scene.add(key);const fill=new THREE.PointLight(0x6df4ff,12,12);fill.position.set(-2,1,4);scene.add(fill);$('.fallback-car').style.opacity='0';let tx=0,ty=0;addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*.28;ty=(e.clientY/innerHeight-.5)*.12});function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(innerWidth<900){car.position.x=1.15;car.scale.setScalar(.72)}else{car.position.x=2.9;car.scale.setScalar(1)}}addEventListener('resize',resize);resize();const clock=new THREE.Clock();(function tick(){const t=clock.getElapsedTime();car.rotation.y+=((-.4+tx)-car.rotation.y)*.045;car.rotation.x+=(ty-car.rotation.x)*.04;car.position.y=-.05+Math.sin(t*.8)*.04;renderer.render(scene,camera);requestAnimationFrame(tick)})()}catch(e){console.warn(e)}}initThree();